version: '3.19'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: danylo
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: test
    networks:
      - patternsLabNet
networks:
  patternsLabNet:
